name: test2

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: verfy hello action work
        uses: hirosi1900day/github-uses-test@master
      - name: Debug
        if: ${{ always() }}
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 15
        with:
            sudo: true
            limit-access-to-actor: true